"""SHA-256 prompt fingerprinting and auto version registration (PRD §8.1, §8.2).

A version is identified by `(slot_name, content_hash)` — hashing the same
template + model params against the same slot always resolves to the same
row, so callers never have to manually bump a version number. The hash is
computed over the *template*, not a rendered instance of it, so re-running
the same template with different variable values links to the same
version rather than minting a new one (PRD §8.1's "dynamic/templated
variation" case). Titles are separate mutable metadata (PRD §8.2):
system-generated by default, renaming one never changes which hash a
version points to.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from typing import Any

from sqlmodel import Field, Session, SQLModel, select

from wisetraceloom.config import get_engine


class PromptVersion(SQLModel, table=True):
    """A registered version of the prompt in logical slot `slot_name`."""

    id: int | None = Field(default=None, primary_key=True)
    slot_name: str = Field(index=True)
    content_hash: str = Field(index=True)
    version_number: int
    title: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


def fingerprint_prompt(template: str, *, model_params: dict[str, Any] | None = None) -> str:
    """SHA-256 hash over the normalized template + model params.

    Normalization only strips formatting noise (surrounding whitespace,
    trailing whitespace per line) so trivial reformatting doesn't register
    as a new version; model params are canonicalized via sorted-key JSON so
    key order never affects the hash.
    """
    normalized_template = "\n".join(line.rstrip() for line in template.strip().splitlines())
    normalized_params = json.dumps(model_params or {}, sort_keys=True, default=str)
    digest_input = f"{normalized_template}\x00{normalized_params}".encode("utf-8")
    return hashlib.sha256(digest_input).hexdigest()


def register_prompt_version(
    slot_name: str,
    template: str,
    *,
    model_params: dict[str, Any] | None = None,
) -> PromptVersion:
    """Auto-detect the version for `template` in `slot_name`: link to the
    existing row with the same content hash, or register a new one with a
    default system-generated title."""
    content_hash = fingerprint_prompt(template, model_params=model_params)

    with Session(get_engine()) as session:
        existing = session.exec(
            select(PromptVersion).where(
                PromptVersion.slot_name == slot_name,
                PromptVersion.content_hash == content_hash,
            )
        ).first()
        if existing is not None:
            return existing

        prior_versions = session.exec(
            select(PromptVersion).where(PromptVersion.slot_name == slot_name)
        ).all()
        version_number = len(prior_versions) + 1
        created_at = datetime.now(timezone.utc)
        title = f"{slot_name} — v{version_number} — {created_at.strftime('%Y-%m-%dT%H:%MZ')}"

        row = PromptVersion(
            slot_name=slot_name,
            content_hash=content_hash,
            version_number=version_number,
            title=title,
            created_at=created_at,
        )
        session.add(row)
        session.commit()
        session.refresh(row)
        return row
